
import { Suspense } from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/headers/header'
import { AnimatedNavigationEvents } from '@/hooks/AnimatedNavigationEvents'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Yesica Giraldo - Aesthetics',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>
          {children}
        </main>
        <Suspense fallback={null}>
          <AnimatedNavigationEvents />
        </Suspense>
      </body>
    </html>
  )
}
